---
title: "workout 3"
output: html_document
author: "Rocky Lubbers"
date: "11/26/18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1 Device
```{r}
#' @title Device
#' @description creates a coin with sides and probability, coin is fair by default
#' @param sides vector of k ≥ 2 elements, by default numbers 1 and 2
#' @param prob vector of probabilities for each side (all equal to 1/2 by default).
#' @return device object
device = function(sides = c(1,2), prob = c(0.5, 0.5)) {
  check_sides(sides)
  check_prob(prob)
  if(length(sides) != length(prob)) {
    stop("'sides' and 'prob' have different lengths")
  }
  dev <- list(sides = sides, prob = prob)
  class(dev) <- "device" #create object classs device, with attributes sides and prob
  return(dev)
}

# print method for objects of class 'device'

#' @title Print Device
#' @description prints the device object
#' @param x a device object
#' @return prints the data frame of the device object with its sides and probabilities
print.device <- function(x) {
  cat('object "device"\n\n')
  side_prob <- data.frame(side = x$sides, prob = x$prob)
  print(side_prob)
}
```

```{r}
#' @title Is Device
#' @description checks if the object is of class device
#' @param x an object
#' @return TRUE if object x is of class 'device', FALSE otherwise
is.device = function(x) {
  if(class(x) == 'device') {
    return(TRUE)
  } else {
    return(FALSE)
  }
}
```

```{r}
#' @title Check Sides
#' @description checks the validity of argument sides in device function
#' @param sides vector of k ≥ 2 elements
#' @return TRUE if sides is a vector with more than 1 element, not containing duplicates. Throws error otherwise. 
check_sides = function(sides) {
  if(length(sides) < 2) {
    stop("'sides' must be a vector of length greater than 1")
  } else if(TRUE %in% duplicated(sides)) {
    stop("'sides' cannot have duplicated elements")
  } else {
    return(TRUE)
  }
}
```

```{r}
#' @title Check Prob
#' @description checks the validity of argument prob in device function
#' @param prob vector of probabilities for each side 
#' @return TRUE if vector is a numeric vector with more than 1 element, 0<x<1, and elements add to 1. Throws error otherwise. 
check_prob = function(prob) {
  if(is.numeric(prob) == FALSE) {
    stop("'prob' is not a numeric vector")
  } else if(length(prob) < 2) {
    stop("'prob' must be a vector of length greater than 1")
  } else if(sum(prob) != 1) {
    stop("elements in 'prob' must add up to 1")
  } else if(any(prob < 0) | any(prob > 1)) {
    stop("elements in 'prob' exceed 1 or are less than 0")
  } else {
    return(TRUE)
  }
}
```



# 2 Object "rolls"
```{r}
#' @title Rolls
#' @description creates and rolls the device for a number of times
#' @param device object of class device (a vector)
#' @param times number of tosses (default value of 1)
#' @return an object of class "rolls"
roll = function(device, times = 1L) {
  if(is.device(device) == FALSE) {
    stop("device is not of class 'device'")
  }
  check_times(times)
  rolls = sample(device$sides, size = times, replace = TRUE, prob = device$prob)
  rollo = list(rolls = rolls, sides = device$sides, prob = device$prob, total = times)
  class(rollo) <- "rolls" #create object classs rolls
  return(rollo)
}

# print method for objects of class 'device'

#' @title Print Rolls
#' @description prints the 'rolls' object
#' @param x a 'roll' object
#' @return the name of the object, as well as the generated rolls
print.rolls <- function(x) {
  cat('object "rolls"\n\n')
  print(x$rolls)
}
```

```{r}
#' @title Check Times
#' @description checks the validity of argument times in device function
#' @param times integer
#' @return TRUE if times is positive integer greater than or equal to 1, ERROR otherwise
check_times = function(times) {
  if(is.numeric(times) == FALSE) {
    stop("'times' is not integer")
  } else if(times < 1) {
    stop("'times' is not a positive integer")
  } else {
    return(TRUE)
  }
}
```

# 3 Summary Object for "Rolls"
```{r}
#' @title Summary Rolls
#' @description takes a 'roll' object and makes a summary of all the data associated with it
#' @param x a 'roll' object
#' @return a dataframe with sides (of rolled 'device'), 
#'        counts (frequency of the number of the roll), and prop (the relative frequencies of each side of the rolled 'device')
summary.rolls <- function(x) {
  count_table = as.data.frame(table(as.factor(x$rolls)))
  prop_table = as.data.frame(prop.table(table(x$rolls)))
  freqs = data.frame(
    side = x$sides,
    count = count_table$Freq,
    prop = prop_table$Freq
  )
  obj <- list(freqs = freqs)
  class(obj) <- "summary.rolls"
  return(obj)
}

#' @title Print Summary Rolls
#' @description prints the summary.rolls object's frequency dataframe
#' @param x a 'summary.roll' object
#' @return the name of the object, as well as the dataframe of side, count, and prop associated with it
print.summary.rolls = function(x) {
  cat('summary "rolls"\n\n')
  print(x$freqs)
}
```


```{r}
#' @title Plot Rolls
#' @description graphs a barchart of the proportions of the sides of devices
#' @param x a 'rolls' object
#' @return the barchart of the proportions
plot.rolls = function(x) {
  x_sum = summary.rolls(x)
  side = x_sum$freq$side
  freqs = x_sum$freqs$prop
  barplot(freqs,
       xlab = "sides of device", bty = "n",
       ylab = sprintf("relative frequencies"), 
       names.arg = 1:length(side))
  title(sprintf("Relative Frequencies in a series of %s rolls", x$total))
}
```


```{r}
# plot method
# roll fair die 50 times
fair_die <- device(sides = 1:6, prob = rep(1/6, 6))
# roll 50 times
set.seed(123)
fair_50rolls <- roll(fair_die, times = 50)
plot(fair_50rolls)
```

```{r}
#' @title Roll Extraction Method
#' @description extracts the index of the roll
#' @param x the 'roll' object
#' @param i the index
#' @return the index of the roll
"[.rolls" <- function(x, i) {
  if (i > x$total) {
    stop("the given index out of bounds")
  }
  x$rolls[i]
}
```

```{r}
#' @title Roll Replacement Method
#' @description replaces the value at index 
#' @param x the 'roll' object 
#' @param i the index 
#' @param value the value to replace the index 
#' @return the new value at the index
"[<-.rolls"  = function(x, i, value) {
  if (i > x$total) {
    stop("the given index out of bounds")
  }
  #x$rolls[i] = value
  x$rolls = replace(x$rolls, list = i, values = value)
  return(x)
}
```

```{r}
#' @title Roll Addition Method
#' @description adds more rolls
#' @param x the 'roll' object 
#' @param i the number of rolls to be added
#' @return adds i number of rolls to the roll object x
"+.rolls" <- function(x, i) {
  if(i <= 0 | length(i) != 1) {s
    stop("added number of rolls must be a postive integer")
  }
  more_rolls = roll(device(x$side, x$prob), times = i)
  x$rolls = c(x$rolls, more_rolls$rolls)
  return(x)
}
```
