---
title: "lab09-rocky-lubbers"
author: "Rocky Lubbers"
date: "10/24/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

```{r}
states <- rownames(USArrests)
head(states)
nchar(states)
tolower(states)
toupper(states)
casefold(states)

# number of charcaters
num_chars <- nchar(states)
char_freqs = table(num_chars)
hist(char_freqs, breaks = 14)
```

```{r}
vec = c(7, 6, 7, 8, 10)
paste(head(states, 5), vec, sep = " = ")
paste(head(states, 5), collapse = '')

#Permutations
factorial(nchar("ALABAMA"))/factorial(3)

substr(states, 1, 3)
substr(states, nchar(states)-2, nchar(states))
paste0(substr(states, 1, 1), substr(states, nchar(states)-2, nchar(states)))

# 4-char states
states[num_chars == 4]

```



```{r}
case = rep("", length(states))
states_list = list()
i = 1 
for(s in states) {
  if(nchar(s) %% 2 == 0) {
    case[i] = toupper(s)
  }
  if(nchar(s) %% 2 == 1) {
    case[i] = tolower(s)
  }
  i = i+1
}
i = 4
for(i in 4:14) {
  l = ''
  for(c in case) {
    if(nchar(c) == i) {
      l = paste(l, c, sep = ', ')
    }
  }
  states_list[i-3] = substring(l, 3)
}
setNames(states_list, paste0(4:14, sep = '-', 'chars'))
```



```{r}
to_celsius <- function(x = 1) {
  (x - 32) * (5/9)
}
to_kelvin <- function(x = 1) {
  (x + 459.67) * (5/9)
}
to_reaumur <- function(x = 1) {
  (x - 32) * (4/9)
}
to_rankine <- function(x = 1) {
  x + 459.67
}

temp_convert <- function(x = 1, to = "celsius") {
  to = tolower(to)
  switch(to,
         "celsius" = to_celsius(x),
         "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}
temp_convert(30, 'celsius')
temp_convert(30, 'Celsius')
temp_convert(30, 'CELSIUS')
```

```{r}
# vector of file names
paste(paste('file', 1:10, sep = ""), 'csv', sep = '.')
file = rep(0, 10)
for(i in 1:10) {
  file[i] = paste(paste('file', i, sep = ""), 'csv', sep = '.')
}
print(file)

i = 0
y = rep(0, 10)
while(i <= 10) {
  y[i] = paste(paste('file', i, sep = ""), 'csv', sep = '.')
  i = i + 1
}
print(y)

# rename vector of file names
x = paste(paste('file', 1:10, sep = ""), 'csv', sep = '.')
sub("file", "dataset", x)
```


```{r}
# name of output file
outfile <- "output.txt"
# writing to 'outfile.txt'
cat("---", file = outfile)
cat("\n", file = outfile, append = TRUE)
cat("title: Lab Output", file = outfile, append = TRUE)
cat("\n", file = outfile, append = TRUE)
cat("author: Rocky Lubbers", file = outfile, append = TRUE)
cat("\n", file = outfile, append = TRUE)
cat("date: 10/24/18", file = outfile, append = TRUE)
cat("\n", file = outfile, append = TRUE)
cat("output: html_document", file = outfile, append = TRUE)
cat("\n", file = outfile, append = TRUE)
cat("---", file = outfile, append = TRUE)
cat("\n\n", file = outfile, append = TRUE)
cat("This is the first line", file = outfile, append = TRUE)
# insert new line
cat("\n", file = outfile, append = TRUE)
cat("This is the first line", append = TRUE)
cat("\n", file = outfile, append = TRUE)
cat("A 2nd line", file = "output.txt", append = TRUE)
# insert 2 new lines
cat("\n\n", file = outfile, append = TRUE)
cat("\nThe quick brown fox jumps over the lazy dog\n",
    file = outfile, append = TRUE)
```


```{r}
# your is_color() function
is_color = function(x) {
  if(x %in% colors()) {
    return(TRUE)
  } else {
    return(FALSE)
  }
}

# test it:
is_color('yellow')  # TRUE
is_color('blu')     # FALSE
is_color('turkuoise') # FALSE
```

```{r}
colplot = function(col) {
  if(is_color(col)) {
    plot(rnorm(50), col = col)
    title(paste("Testing color", col))
  } else {
    stop(paste("Invalid color", col))
  }
  
}
# this should plot
colplot('tomato')

# this stops with error message
colplot('tomate')
```

